from app.services.language_drivers.base import BaseLanguageDriver

class CLanguageDriver(BaseLanguageDriver):
    def build_payload(
        self,
        problem_id: str,
        user_code: str,
        marker: str,
        tests: list[dict[str, str]],
    ) -> dict:
        driver = [
            "#include <stdio.h>",
            "#include <stdlib.h>",
            "#include <string.h>",
            "#include <stdbool.h>",
            "#include <math.h>",
            "",
            "struct ListNode {",
            "    int val;",
            "    struct ListNode *next;",
            "};",
            "",
            "struct ListNode* toList(int* arr, int size) {",
            "    struct ListNode* head = NULL;",
            "    for (int i = size - 1; i >= 0; i--) {",
            "        struct ListNode* node = (struct ListNode*)malloc(sizeof(struct ListNode));",
            "        node->val = arr[i];",
            "        node->next = head;",
            "        head = node;",
            "    }",
            "    return head;",
            "}",
            "",
            "void printList(struct ListNode* node) {",
            "    printf(\"[\");",
            "    while (node != NULL) {",
            "        printf(\"%d\", node->val);",
            "        if (node->next != NULL) printf(\", \");",
            "        node = node->next;",
            "    }",
            "    printf(\"]\");",
            "}",
            "",
            "int formatList(struct ListNode* node, char* buf) {",
            "    int offset = sprintf(buf, \"[\");",
            "    while (node != NULL) {",
            "        offset += sprintf(buf + offset, \"%d\", node->val);",
            "        if (node->next != NULL) offset += sprintf(buf + offset, \", \");",
            "        node = node->next;",
            "    }",
            "    offset += sprintf(buf + offset, \"]\");",
            "    return offset;",
            "}",
            "",
            user_code,
            "",
            "int main() {",
            "    int passed = 0;",
            "    int total = 0;",
        ]

        if problem_id == "001":
            driver.extend([
                "    // Test 1",
                "    {",
                "        total++;",
                "        printf(\"Test 1:\\n\");",
                "        printf(\"Input: nums = [2,7,11,15], target = 9\\n\");",
                "        printf(\"Expected: [0, 1]\\n\");",
                "        int returnSize = 0;",
                "        int nums[] = {2, 7, 11, 15};",
                "        int* res = twoSum(nums, 4, 9, &returnSize);",
                "        printf(\"Actual: [\");",
                "        for (int i = 0; i < returnSize; i++) {",
                "            printf(\"%d\", res[i]);",
                "            if (i + 1 < returnSize) printf(\", \");",
                "        }",
                "        printf(\"]\\n\");",
                "        if (res != NULL && returnSize == 2 && ((res[0] == 0 && res[1] == 1) || (res[0] == 1 && res[1] == 0))) {",
                "            passed++;",
                "            printf(\"Verdict: PASS\\n\");",
                "        } else {",
                "            printf(\"Verdict: FAIL\\n\");",
                "        }",
                "        if (res != NULL) free(res);",
                "    }",
                "    printf(\"\\n\");",
                "    // Test 2",
                "    {",
                "        total++;",
                "        printf(\"Test 2:\\n\");",
                "        printf(\"Input: nums = [3,2,4], target = 6\\n\");",
                "        printf(\"Expected: [1, 2]\\n\");",
                "        int returnSize = 0;",
                "        int nums[] = {3, 2, 4};",
                "        int* res = twoSum(nums, 3, 6, &returnSize);",
                "        printf(\"Actual: [\");",
                "        for (int i = 0; i < returnSize; i++) {",
                "            printf(\"%d\", res[i]);",
                "            if (i + 1 < returnSize) printf(\", \");",
                "        }",
                "        printf(\"]\\n\");",
                "        if (res != NULL && returnSize == 2 && ((res[0] == 1 && res[1] == 2) || (res[0] == 2 && res[1] == 1))) {",
                "            passed++;",
                "            printf(\"Verdict: PASS\\n\");",
                "        } else {",
                "            printf(\"Verdict: FAIL\\n\");",
                "        }",
                "        if (res != NULL) free(res);",
                "    }",
                "    printf(\"\\n\");",
                "    // Test 3",
                "    {",
                "        total++;",
                "        printf(\"Test 3:\\n\");",
                "        printf(\"Input: nums = [3,3], target = 6\\n\");",
                "        printf(\"Expected: [0, 1]\\n\");",
                "        int returnSize = 0;",
                "        int nums[] = {3, 3};",
                "        int* res = twoSum(nums, 2, 6, &returnSize);",
                "        printf(\"Actual: [\");",
                "        for (int i = 0; i < returnSize; i++) {",
                "            printf(\"%d\", res[i]);",
                "            if (i + 1 < returnSize) printf(\", \");",
                "        }",
                "        printf(\"]\\n\");",
                "        if (res != NULL && returnSize == 2 && ((res[0] == 0 && res[1] == 1) || (res[0] == 1 && res[1] == 0))) {",
                "            passed++;",
                "            printf(\"Verdict: PASS\\n\");",
                "        } else {",
                "            printf(\"Verdict: FAIL\\n\");",
                "        }",
                "        if (res != NULL) free(res);",
                "    }",
                "    printf(\"\\n\");",
            ])
        elif problem_id == "002":
            driver.extend([
                "    {",
                "        total++;",
                "        printf(\"Test 1:\\n\");",
                "        printf(\"Input: l1 = [2,4,3], l2 = [5,6,4]\\n\");",
                "        printf(\"Expected: [7, 0, 8]\\n\");",
                "        struct ListNode* l1 = toList((int[]){2,4,3}, 3);",
                "        struct ListNode* l2 = toList((int[]){5,6,4}, 3);",
                "        struct ListNode* res = addTwoNumbers(l1, l2);",
                "        char actual[128];",
                "        formatList(res, actual);",
                "        printf(\"Actual: %s\\n\", actual);",
                "        if (res && res->val == 7 && res->next && res->next->val == 0 && res->next->next && res->next->next->val == 8 && !res->next->next->next) {",
                "            passed++;",
                "            printf(\"Verdict: PASS\\n\");",
                "        } else {",
                "            printf(\"Verdict: FAIL\\n\");",
                "        }",
                "    }",
            ])
        elif problem_id == "003":
            driver.extend([
                "    {",
                "        total++;",
                "        printf(\"Test 1:\\n\");",
                "        printf(\"Input: s = \\\"abcabcbb\\\"\\n\");",
                "        printf(\"Expected: 3\\n\");",
                "        int res = lengthOfLongestSubstring(\"abcabcbb\");",
                "        printf(\"Actual: %d\\n\", res);",
                "        if (res == 3) {",
                "            passed++;",
                "            printf(\"Verdict: PASS\\n\");",
                "        } else {",
                "            printf(\"Verdict: FAIL\\n\");",
                "        }",
                "    }",
            ])
        elif problem_id == "004":
            driver.extend([
                "    {",
                "        total++;",
                "        printf(\"Test 1:\\n\");",
                "        printf(\"Input: nums1 = [1,3], nums2 = [2]\\n\");",
                "        printf(\"Expected: 2.0\\n\");",
                "        double res = findMedianSortedArrays((int[]){1,3}, 2, (int[]){2}, 1);",
                "        printf(\"Actual: %.1f\\n\", res);",
                "        if (fabs(res - 2.0) < 1e-6) {",
                "            passed++;",
                "            printf(\"Verdict: PASS\\n\");",
                "        } else {",
                "            printf(\"Verdict: FAIL\\n\");",
                "        }",
                "    }",
            ])
        elif problem_id == "005":
            driver.extend([
                "    {",
                "        total++;",
                "        printf(\"Test 1:\\n\");",
                "        printf(\"Input: s = \\\"babad\\\"\\n\");",
                "        printf(\"Expected: bab\\n\");",
                "        char* res = longestPalindrome(\"babad\");",
                "        printf(\"Actual: %s\\n\", res ? res : \"(null)\");",
                "        if (res && (strcmp(res, \"bab\") == 0 || strcmp(res, \"aba\") == 0)) {",
                "            passed++;",
                "            printf(\"Verdict: PASS\\n\");",
                "        } else {",
                "            printf(\"Verdict: FAIL\\n\");",
                "        }",
                "    }",
            ])
        elif problem_id == "006":
            driver.extend([
                "    {",
                "        total++;",
                "        printf(\"Test 1:\\n\");",
                "        printf(\"Input: s = \\\"PAYPALISHIRING\\\", numRows = 3\\n\");",
                "        printf(\"Expected: PAHNAPLSIIGYIR\\n\");",
                "        char* res = convert(\"PAYPALISHIRING\", 3);",
                "        printf(\"Actual: %s\\n\", res ? res : \"(null)\");",
                "        if (res && strcmp(res, \"PAHNAPLSIIGYIR\") == 0) {",
                "            passed++;",
                "            printf(\"Verdict: PASS\\n\");",
                "        } else {",
                "            printf(\"Verdict: FAIL\\n\");",
                "        }",
                "    }",
            ])
        elif problem_id == "007":
            driver.extend([
                "    {",
                "        total++;",
                "        printf(\"Test 1:\\n\");",
                "        printf(\"Input: x = 123\\n\");",
                "        printf(\"Expected: 321\\n\");",
                "        int res = reverse(123);",
                "        printf(\"Actual: %d\\n\", res);",
                "        if (res == 321) {",
                "            passed++;",
                "            printf(\"Verdict: PASS\\n\");",
                "        } else {",
                "            printf(\"Verdict: FAIL\\n\");",
                "        }",
                "    }",
            ])
        elif problem_id == "008":
            driver.extend([
                "    {",
                "        total++;",
                "        printf(\"Test 1:\\n\");",
                "        printf(\"Input: s = \\\"42\\\"\\n\");",
                "        printf(\"Expected: 42\\n\");",
                "        int res = myAtoi(\"42\");",
                "        printf(\"Actual: %d\\n\", res);",
                "        if (res == 42) {",
                "            passed++;",
                "            printf(\"Verdict: PASS\\n\");",
                "        } else {",
                "            printf(\"Verdict: FAIL\\n\");",
                "        }",
                "    }",
            ])
        elif problem_id == "009":
            driver.extend([
                "    {",
                "        total++;",
                "        printf(\"Test 1:\\n\");",
                "        printf(\"Input: x = 121\\n\");",
                "        printf(\"Expected: true\\n\");",
                "        bool res = isPalindrome(121);",
                "        printf(\"Actual: %s\\n\", res ? \"true\" : \"false\");",
                "        if (res) {",
                "            passed++;",
                "            printf(\"Verdict: PASS\\n\");",
                "        } else {",
                "            printf(\"Verdict: FAIL\\n\");",
                "        }",
                "    }",
            ])

        driver.extend([
            f"    printf(\"{marker}{{\\\"testsPassed\\\":%d,\\\"totalTests\\\":%d}}\\n\", passed, total);",
            "    return 0;",
            "}"
        ])
        return {
            "files": {
                "solution.c": "\n".join(driver)
            },
            "compile_cmd": "gcc -O3 solution.c -o solution",
            "run_cmd": "./solution"
        }
