from app.services.language_drivers.base import BaseLanguageDriver

class CppLanguageDriver(BaseLanguageDriver):
    def build_payload(
        self,
        problem_id: str,
        user_code: str,
        marker: str,
        tests: list[dict[str, str]],
    ) -> dict:
        driver = [
            "#include <iostream>",
            "#include <vector>",
            "#include <string>",
            "#include <algorithm>",
            "#include <cmath>",
            "",
            "struct ListNode {",
            "    int val;",
            "    ListNode *next;",
            "    ListNode() : val(0), next(nullptr) {}",
            "    ListNode(int x) : val(x), next(nullptr) {}",
            "    ListNode(int x, ListNode *next) : val(x), next(next) {}",
            "};",
            "",
            "ListNode* toList(const std::vector<int>& arr) {",
            "    ListNode* head = nullptr;",
            "    for (int i = (int)arr.size() - 1; i >= 0; i--) {",
            "        head = new ListNode(arr[i], head);",
            "    }",
            "    return head;",
            "}",
            "",
            "std::string format(ListNode* node) {",
            "    std::string res = \"[\";",
            "    while (node != nullptr) {",
            "        res += std::to_string(node->val);",
            "        if (node->next != nullptr) res += \", \";",
            "        node = node->next;",
            "    }",
            "    res += \"]\";",
            "    return res;",
            "}",
            "",
            user_code,
            "",
            "int main() {",
            "    Solution solver;",
            "    int passed = 0;",
            "    int total = 0;",
        ]
        
        if problem_id == "001":
            driver.extend([
                "    // Test 1",
                "    try {",
                "        total++;",
                "        std::cout << \"Test 1:\\n\";",
                "        std::cout << \"Input: nums = [2,7,11,15], target = 9\\n\";",
                "        std::cout << \"Expected: [0, 1]\\n\";",
                "        std::vector<int> nums = {2,7,11,15};",
                "        std::vector<int> res = solver.twoSum(nums, 9);",
                "        std::cout << \"Actual: [\";",
                "        for (size_t i = 0; i < res.size(); i++) {",
                "            std::cout << res[i] << (i + 1 < res.size() ? \", \" : \"\");",
                "        }",
                "        std::cout << \"]\\n\";",
                "        if (res.size() == 2 && ((res[0] == 0 && res[1] == 1) || (res[0] == 1 && res[1] == 0))) {",
                "            passed++;",
                "            std::cout << \"Verdict: PASS\\n\";",
                "        } else {",
                "            std::cout << \"Verdict: FAIL\\n\";",
                "        }",
                "    } catch (...) {",
                "        std::cout << \"Verdict: ERROR\\n\";",
                "    }",
                "    std::cout << \"\\n\";",
                "    // Test 2",
                "    try {",
                "        total++;",
                "        std::cout << \"Test 2:\\n\";",
                "        std::cout << \"Input: nums = [3,2,4], target = 6\\n\";",
                "        std::cout << \"Expected: [1, 2]\\n\";",
                "        std::vector<int> nums = {3,2,4};",
                "        std::vector<int> res = solver.twoSum(nums, 6);",
                "        std::cout << \"Actual: [\";",
                "        for (size_t i = 0; i < res.size(); i++) {",
                "            std::cout << res[i] << (i + 1 < res.size() ? \", \" : \"\");",
                "        }",
                "        std::cout << \"]\\n\";",
                "        if (res.size() == 2 && ((res[0] == 1 && res[1] == 2) || (res[0] == 2 && res[1] == 1))) {",
                "            passed++;",
                "            std::cout << \"Verdict: PASS\\n\";",
                "        } else {",
                "            std::cout << \"Verdict: FAIL\\n\";",
                "        }",
                "    } catch (...) {",
                "        std::cout << \"Verdict: ERROR\\n\";",
                "    }",
                "    std::cout << \"\\n\";",
                "    // Test 3",
                "    try {",
                "        total++;",
                "        std::cout << \"Test 3:\\n\";",
                "        std::cout << \"Input: nums = [3,3], target = 6\\n\";",
                "        std::cout << \"Expected: [0, 1]\\n\";",
                "        std::vector<int> nums = {3,3};",
                "        std::vector<int> res = solver.twoSum(nums, 6);",
                "        std::cout << \"Actual: [\";",
                "        for (size_t i = 0; i < res.size(); i++) {",
                "            std::cout << res[i] << (i + 1 < res.size() ? \", \" : \"\");",
                "        }",
                "        std::cout << \"]\\n\";",
                "        if (res.size() == 2 && ((res[0] == 0 && res[1] == 1) || (res[0] == 1 && res[1] == 0))) {",
                "            passed++;",
                "            std::cout << \"Verdict: PASS\\n\";",
                "        } else {",
                "            std::cout << \"Verdict: FAIL\\n\";",
                "        }",
                "    } catch (...) {",
                "        std::cout << \"Verdict: ERROR\\n\";",
                "    }",
                "    std::cout << \"\\n\";",
            ])
        elif problem_id == "002":
            driver.extend([
                "    try {",
                "        total++;",
                "        std::cout << \"Test 1:\\n\";",
                "        std::cout << \"Input: l1 = [2,4,3], l2 = [5,6,4]\\n\";",
                "        std::cout << \"Expected: [7, 0, 8]\\n\";",
                "        ListNode* res = solver.addTwoNumbers(toList({2,4,3}), toList({5,6,4}));",
                "        std::string actual = format(res);",
                "        std::cout << \"Actual: \" << actual << \"\\n\";",
                "        if (actual == \"[7, 0, 8]\") {",
                "            passed++;",
                "            std::cout << \"Verdict: PASS\\n\";",
                "        } else {",
                "            std::cout << \"Verdict: FAIL\\n\";",
                "        }",
                "    } catch (...) {",
                "        std::cout << \"Verdict: ERROR\\n\";",
                "    }",
            ])
        elif problem_id == "003":
            driver.extend([
                "    try {",
                "        total++;",
                "        std::cout << \"Test 1:\\n\";",
                "        std::cout << \"Input: s = \\\"abcabcbb\\\"\\n\";",
                "        std::cout << \"Expected: 3\\n\";",
                "        int res = solver.lengthOfLongestSubstring(\"abcabcbb\");",
                "        std::cout << \"Actual: \" << res << \"\\n\";",
                "        if (res == 3) {",
                "            passed++;",
                "            std::cout << \"Verdict: PASS\\n\";",
                "        } else {",
                "            std::cout << \"Verdict: FAIL\\n\";",
                "        }",
                "    } catch (...) {",
                "        std::cout << \"Verdict: ERROR\\n\";",
                "    }",
            ])
        elif problem_id == "004":
            driver.extend([
                "    try {",
                "        total++;",
                "        std::cout << \"Test 1:\\n\";",
                "        std::cout << \"Input: nums1 = [1,3], nums2 = [2]\\n\";",
                "        std::cout << \"Expected: 2.0\\n\";",
                "        std::vector<int> n1 = {1,3};",
                "        std::vector<int> n2 = {2};",
                "        double res = solver.findMedianSortedArrays(n1, n2);",
                "        std::cout << \"Actual: \" << res << \"\\n\";",
                "        if (std::abs(res - 2.0) < 1e-6) {",
                "            passed++;",
                "            std::cout << \"Verdict: PASS\\n\";",
                "        } else {",
                "            std::cout << \"Verdict: FAIL\\n\";",
                "        }",
                "    } catch (...) {",
                "        std::cout << \"Verdict: ERROR\\n\";",
                "    }",
            ])
        elif problem_id == "005":
            driver.extend([
                "    try {",
                "        total++;",
                "        std::cout << \"Test 1:\\n\";",
                "        std::cout << \"Input: s = \\\"babad\\\"\\n\";",
                "        std::cout << \"Expected: bab\\n\";",
                "        std::string res = solver.longestPalindrome(\"babad\");",
                "        std::cout << \"Actual: \" << res << \"\\n\";",
                "        if (res == \"bab\" || res == \"aba\") {",
                "            passed++;",
                "            std::cout << \"Verdict: PASS\\n\";",
                "        } else {",
                "            std::cout << \"Verdict: FAIL\\n\";",
                "        }",
                "    } catch (...) {",
                "        std::cout << \"Verdict: ERROR\\n\";",
                "    }",
            ])
        elif problem_id == "006":
            driver.extend([
                "    try {",
                "        total++;",
                "        std::cout << \"Test 1:\\n\";",
                "        std::cout << \"Input: s = \\\"PAYPALISHIRING\\\", numRows = 3\\n\";",
                "        std::cout << \"Expected: PAHNAPLSIIGYIR\\n\";",
                "        std::string res = solver.convert(\"PAYPALISHIRING\", 3);",
                "        std::cout << \"Actual: \" << res << \"\\n\";",
                "        if (res == \"PAHNAPLSIIGYIR\") {",
                "            passed++;",
                "            std::cout << \"Verdict: PASS\\n\";",
                "        } else {",
                "            std::cout << \"Verdict: FAIL\\n\";",
                "        }",
                "    } catch (...) {",
                "        std::cout << \"Verdict: ERROR\\n\";",
                "    }",
            ])
        elif problem_id == "007":
            driver.extend([
                "    try {",
                "        total++;",
                "        std::cout << \"Test 1:\\n\";",
                "        std::cout << \"Input: x = 123\\n\";",
                "        std::cout << \"Expected: 321\\n\";",
                "        int res = solver.reverse(123);",
                "        std::cout << \"Actual: \" << res << \"\\n\";",
                "        if (res == 321) {",
                "            passed++;",
                "            std::cout << \"Verdict: PASS\\n\";",
                "        } else {",
                "            std::cout << \"Verdict: FAIL\\n\";",
                "        }",
                "    } catch (...) {",
                "        std::cout << \"Verdict: ERROR\\n\";",
                "    }",
            ])
        elif problem_id == "008":
            driver.extend([
                "    try {",
                "        total++;",
                "        std::cout << \"Test 1:\\n\";",
                "        std::cout << \"Input: s = \\\"42\\\"\\n\";",
                "        std::cout << \"Expected: 42\\n\";",
                "        int res = solver.myAtoi(\"42\");",
                "        std::cout << \"Actual: \" << res << \"\\n\";",
                "        if (res == 42) {",
                "            passed++;",
                "            std::cout << \"Verdict: PASS\\n\";",
                "        } else {",
                "            std::cout << \"Verdict: FAIL\\n\";",
                "        }",
                "    } catch (...) {",
                "        std::cout << \"Verdict: ERROR\\n\";",
                "    }",
            ])
        elif problem_id == "009":
            driver.extend([
                "    try {",
                "        total++;",
                "        std::cout << \"Test 1:\\n\";",
                "        std::cout << \"Input: x = 121\\n\";",
                "        std::cout << \"Expected: true\\n\";",
                "        bool res = solver.isPalindrome(121);",
                "        std::cout << \"Actual: \" << (res ? \"true\" : \"false\") << \"\\n\";",
                "        if (res) {",
                "            passed++;",
                "            std::cout << \"Verdict: PASS\\n\";",
                "        } else {",
                "            std::cout << \"Verdict: FAIL\\n\";",
                "        }",
                "    } catch (...) {",
                "        std::cout << \"Verdict: ERROR\\n\";",
                "    }",
            ])

        driver.extend([
            f"    std::cout << \"{marker}\" << \"{{\\\"testsPassed\\\":\" << passed << \",\\\"totalTests\\\":\" << total << \"}}\\n\";",
            "    return 0;",
            "}"
        ])
        return {
            "files": {
                "solution.cpp": "\n".join(driver)
            },
            "compile_cmd": "g++ -O3 solution.cpp -o solution",
            "run_cmd": "./solution"
        }
