from app.services.language_drivers.base import BaseLanguageDriver

class JavaLanguageDriver(BaseLanguageDriver):
    def build_payload(
        self,
        problem_id: str,
        user_code: str,
        marker: str,
        tests: list[dict[str, str]],
    ) -> dict:
        driver = [
            "import java.util.*;",
            "",
            "class ListNode {",
            "    int val;",
            "    ListNode next;",
            "    ListNode() {}",
            "    ListNode(int val) { this.val = val; }",
            "    ListNode(int val, ListNode next) { this.val = val; this.next = next; }",
            "}",
            "",
            user_code,
            "",
            "public class Driver {",
            "    public static ListNode toList(int[] arr) {",
            "        ListNode head = null;",
            "        for (int i = arr.length - 1; i >= 0; i--) {",
            "            head = new ListNode(arr[i], head);",
            "        }",
            "        return head;",
            "    }",
            "",
            "    public static String format(ListNode node) {",
            "        List<Integer> arr = new ArrayList<>();",
            "        while (node != null) {",
            "            arr.add(node.val);",
            "            node = node.next;",
            "        }",
            "        return arr.toString();",
            "    }",
            "",
            "    public static void main(String[] args) {",
            "        Solution solver = new Solution();",
            "        int passed = 0;",
            "        int total = 0;",
        ]

        if problem_id == "001":
            driver.extend([
                "        // Test 1",
                "        try {",
                "            total++;",
                "            System.out.println(\"Test 1:\");",
                "            System.out.println(\"Input: nums = [2,7,11,15], target = 9\");",
                "            System.out.println(\"Expected: [0, 1]\");",
                "            int[] res = solver.twoSum(new int[]{2,7,11,15}, 9);",
                "            System.out.println(\"Actual: \" + Arrays.toString(res));",
                "            if (res != null && res.length == 2 && ((res[0] == 0 && res[1] == 1) || (res[0] == 1 && res[1] == 0))) {",
                "                passed++;",
                "                System.out.println(\"Verdict: PASS\");",
                "            } else {",
                "                System.out.println(\"Verdict: FAIL\");",
                "            }",
                "        } catch (Exception e) {",
                "            System.out.println(\"Verdict: ERROR\");",
                "        }",
                "        System.out.println();",
                "        // Test 2",
                "        try {",
                "            total++;",
                "            System.out.println(\"Test 2:\");",
                "            System.out.println(\"Input: nums = [3,2,4], target = 6\");",
                "            System.out.println(\"Expected: [1, 2]\");",
                "            int[] res = solver.twoSum(new int[]{3,2,4}, 6);",
                "            System.out.println(\"Actual: \" + Arrays.toString(res));",
                "            if (res != null && res.length == 2 && ((res[0] == 1 && res[1] == 2) || (res[0] == 2 && res[1] == 1))) {",
                "                passed++;",
                "                System.out.println(\"Verdict: PASS\");",
                "            } else {",
                "                System.out.println(\"Verdict: FAIL\");",
                "            }",
                "        } catch (Exception e) {",
                "            System.out.println(\"Verdict: ERROR\");",
                "        }",
                "        System.out.println();",
                "        // Test 3",
                "        try {",
                "            total++;",
                "            System.out.println(\"Test 3:\");",
                "            System.out.println(\"Input: nums = [3,3], target = 6\");",
                "            System.out.println(\"Expected: [0, 1]\");",
                "            int[] res = solver.twoSum(new int[]{3,3}, 6);",
                "            System.out.println(\"Actual: \" + Arrays.toString(res));",
                "            if (res != null && res.length == 2 && ((res[0] == 0 && res[1] == 1) || (res[0] == 1 && res[1] == 0))) {",
                "                passed++;",
                "                System.out.println(\"Verdict: PASS\");",
                "            } else {",
                "                System.out.println(\"Verdict: FAIL\");",
                "            }",
                "        } catch (Exception e) {",
                "            System.out.println(\"Verdict: ERROR\");",
                "        }",
                "        System.out.println();",
            ])
        elif problem_id == "002":
            driver.extend([
                "        try {",
                "            total++;",
                "            System.out.println(\"Test 1:\");",
                "            System.out.println(\"Input: l1 = [2,4,3], l2 = [5,6,4]\");",
                "            System.out.println(\"Expected: [7, 0, 8]\");",
                "            ListNode res = solver.addTwoNumbers(toList(new int[]{2,4,3}), toList(new int[]{5,6,4}));",
                "            String actual = format(res);",
                "            System.out.println(\"Actual: \" + actual);",
                "            if (\"[7, 0, 8]\".replace(\" \", \"\").equals(actual.replace(\" \", \"\"))) {",
                "                passed++;",
                "                System.out.println(\"Verdict: PASS\");",
                "            } else {",
                "                System.out.println(\"Verdict: FAIL\");",
                "            }",
                "        } catch (Exception e) {",
                "            System.out.println(\"Verdict: ERROR\");",
                "        }",
            ])
        elif problem_id == "003":
            driver.extend([
                "        try {",
                "            total++;",
                "            System.out.println(\"Test 1:\");",
                "            System.out.println(\"Input: s = \\\"abcabcbb\\\"\");",
                "            System.out.println(\"Expected: 3\");",
                "            int res = solver.lengthOfLongestSubstring(\"abcabcbb\");",
                "            System.out.println(\"Actual: \" + res);",
                "            if (res == 3) {",
                "                passed++;",
                "                System.out.println(\"Verdict: PASS\");",
                "            } else {",
                "                System.out.println(\"Verdict: FAIL\");",
                "            }",
                "        } catch (Exception e) {",
                "            System.out.println(\"Verdict: ERROR\");",
                "        }",
            ])
        elif problem_id == "004":
            driver.extend([
                "        try {",
                "            total++;",
                "            System.out.println(\"Test 1:\");",
                "            System.out.println(\"Input: nums1 = [1,3], nums2 = [2]\");",
                "            System.out.println(\"Expected: 2.0\");",
                "            double res = solver.findMedianSortedArrays(new int[]{1,3}, new int[]{2});",
                "            System.out.println(\"Actual: \" + res);",
                "            if (Math.abs(res - 2.0) < 1e-6) {",
                "                passed++;",
                "                System.out.println(\"Verdict: PASS\");",
                "            } else {",
                "                System.out.println(\"Verdict: FAIL\");",
                "            }",
                "        } catch (Exception e) {",
                "            System.out.println(\"Verdict: ERROR\");",
                "        }",
            ])
        elif problem_id == "005":
            driver.extend([
                "        try {",
                "            total++;",
                "            System.out.println(\"Test 1:\");",
                "            System.out.println(\"Input: s = \\\"babad\\\"\");",
                "            System.out.println(\"Expected: bab\");",
                "            String res = solver.longestPalindrome(\"babad\");",
                "            System.out.println(\"Actual: \" + res);",
                "            if (\"bab\".equals(res) || \"aba\".equals(res)) {",
                "                passed++;",
                "                System.out.println(\"Verdict: PASS\");",
                "            } else {",
                "                System.out.println(\"Verdict: FAIL\");",
                "            }",
                "        } catch (Exception e) {",
                "            System.out.println(\"Verdict: ERROR\");",
                "        }",
            ])
        elif problem_id == "006":
            driver.extend([
                "        try {",
                "            total++;",
                "            System.out.println(\"Test 1:\");",
                "            System.out.println(\"Input: s = \\\"PAYPALISHIRING\\\", numRows = 3\");",
                "            System.out.println(\"Expected: PAHNAPLSIIGYIR\");",
                "            String res = solver.convert(\"PAYPALISHIRING\", 3);",
                "            System.out.println(\"Actual: \" + res);",
                "            if (\"PAHNAPLSIIGYIR\".equals(res)) {",
                "                passed++;",
                "                System.out.println(\"Verdict: PASS\");",
                "            } else {",
                "                System.out.println(\"Verdict: FAIL\");",
                "            }",
                "        } catch (Exception e) {",
                "            System.out.println(\"Verdict: ERROR\");",
                "        }",
            ])
        elif problem_id == "007":
            driver.extend([
                "        try {",
                "            total++;",
                "            System.out.println(\"Test 1:\");",
                "            System.out.println(\"Input: x = 123\");",
                "            System.out.println(\"Expected: 321\");",
                "            int res = solver.reverse(123);",
                "            System.out.println(\"Actual: \" + res);",
                "            if (res == 321) {",
                "                passed++;",
                "                System.out.println(\"Verdict: PASS\");",
                "            } else {",
                "                System.out.println(\"Verdict: FAIL\");",
                "            }",
                "        } catch (Exception e) {",
                "            System.out.println(\"Verdict: ERROR\");",
                "        }",
            ])
        elif problem_id == "008":
            driver.extend([
                "        try {",
                "            total++;",
                "            System.out.println(\"Test 1:\");",
                "            System.out.println(\"Input: s = \\\"42\\\"\");",
                "            System.out.println(\"Expected: 42\");",
                "            int res = solver.myAtoi(\"42\");",
                "            System.out.println(\"Actual: \" + res);",
                "            if (res == 42) {",
                "                passed++;",
                "                System.out.println(\"Verdict: PASS\");",
                "            } else {",
                "                System.out.println(\"Verdict: FAIL\");",
                "            }",
                "        } catch (Exception e) {",
                "            System.out.println(\"Verdict: ERROR\");",
                "        }",
            ])
        elif problem_id == "009":
            driver.extend([
                "        try {",
                "            total++;",
                "            System.out.println(\"Test 1:\");",
                "            System.out.println(\"Input: x = 121\");",
                "            System.out.println(\"Expected: true\");",
                "            boolean res = solver.isPalindrome(121);",
                "            System.out.println(\"Actual: \" + res);",
                "            if (res) {",
                "                passed++;",
                "                System.out.println(\"Verdict: PASS\");",
                "            } else {",
                "                System.out.println(\"Verdict: FAIL\");",
                "            }",
                "        } catch (Exception e) {",
                "            System.out.println(\"Verdict: ERROR\");",
                "        }",
            ])

        driver.extend([
            f"        System.out.println(\"{marker}\" + \"{{\\\"testsPassed\\\":\" + passed + \",\\\"totalTests\\\":\" + total + \"}}\");",
            "    }",
            "}"
        ])
        return {
            "files": {
                "Driver.java": "\n".join(driver)
            },
            "compile_cmd": "javac Driver.java",
            "run_cmd": "java Driver"
        }
